### ISSUE TITLE
Investigate Arduino board

### ISSUE THREAD

**Issue by SuneJepsen** [SuneJepsen/iotproject-arduino#1]
Investigate the setup of Arduino boards

**Comment by Spiderixius** [comment]
I am unable to get the board to be recognized by Windows 10. I have tried this on three different computers with three different USB cables and all USB ports.

Following is the error;

![image](https://user-images.githubusercontent.com/10165995/37862314-24be7796-2f4b-11e8-8555-bc89b7bc2514.png)

I have tried installing drivers and such and exact same issue each time. I followed the user guide step by step, which can be found on Blackboard.

**Comment by Spiderixius** [comment]
Error has been fixed
![image](https://user-images.githubusercontent.com/10165995/38452688-4fe65246-3a49-11e8-948d-3838922ca79f.png)

**Comment by Spiderixius** [comment]
Ameltech https://github.com/ameltech contains the libraries needed to be able to work with the electronic components on the board.

Specifically for proximity and accelerometer following are important libraries: 
**Proximity**: https://github.com/ameltech/sme-vl6180x-library 
**Accelerometer**: https://github.com/ameltech/sme-lsm9ds1-library

**Comment by Spiderixius** [comment]
Sigfox modem, see https://www.telit.com/wp-content/uploads/2017/09/Telit_LE51-868_S_Software_User_Guide_r3.pdf
and http://docs-europe.electrocomponents.com/webdocs/144b/0900766b8144b09d.pdf looks like a pretty good overall guide for the SmartEverything board.

**Comment by SuneJepsen** [comment]
good work @Spiderixius 👍
