### ISSUE TITLE
Retrieve sensor data (movement, accelerometer, WiFi/BLE)

### ISSUE THREAD

**Issue by SuneJepsen** [SuneJepsen/iotproject-arduino#2]
Setup retrieval of sensor data from the following sensors
- Proximity
- Accelerometer
- Bluetooth Beacons Scan (later)

**Comment by Spiderixius** [comment]
Proximity and Accelerometer is completed. See https://github.com/SuneJepsen/iotproject-arduino/tree/master/Accelerometer and https://github.com/SuneJepsen/iotproject-arduino/tree/master/Proximity for the implementation.
