### ISSUE TITLE
Connect SigFox to external database

### ISSUE THREAD

**Issue by SuneJepsen** [SuneJepsen/iotproject-arduino#3]
Setup SigFox account and reroute all data to the raw data DB (firebase?)
Investigate bandwidth and calls to use with Sigfox

**Comment by Spiderixius** [comment]
It seems it is possible to connect Sigfox to Firebase via a Custom Callback: https://ask.sigfox.com/questions/5053/custom-callback-firebase.html

**Comment by Spiderixius** [comment]
Completed, Sigfox sends whatever you give it to Firebase.
