### ISSUE TITLE
Implement sensor data logic for pushing

### ISSUE THREAD

**Issue by anna0207** [SuneJepsen/iotproject-arduino#6]
Investigate how to get current timestamp from Arduino

Implement threshold logic:
- Proximity: Push data after collected sensor data is above and then below threshold
     - Timestamp for start and end of movement
- Accelerometer: Push data after collected sensor data detects door open and then door closed
     - Timestamp for door open (movement in one direction) and door close (movement in opposite direction)

![iot](https://user-images.githubusercontent.com/10400529/38418078-3a569f3e-399b-11e8-9904-73ee0fc9be77.PNG)

**Comment by anna0207** [comment]
Discussion with Aslak: Signal processing and prototype how the data can infer people walking in and out. Average, max, noise detection, signal processing (how much on arduino board and how muc hin the cloud?)

**Comment by Spiderixius** [comment]
It seems time can be controlled via the following library http://playground.arduino.cc/Code/Time . It has yet to be tested.

**Comment by anna0207** [comment]
Time synchronizing between devices and Sigfox:
- Choice 1: Send start and end count from Arduino to Sigfox - and sigfox sets current timestamp + rssi with counts in firebase
      - .NET layer will calculate timestamp from timestamp and rssi from EVERY counts
- Choice 2: When Arduino program begins send a "handshake" message to sigfox - and sigfox sets current timestamp with rssi in firebase.
      - .NET layer will calculate timestamp from INITIAL timestamp and rssi for ALL counts

Evaluate a function to determine latency based on RSSI

Pros and Cons:
- Choice 1: More computation (needs to compute latency for every entry) + can have bad calculations (not aware of which is bad or good - calibration will not fix this)
- Choice 2: Less computation (only compute latency once) + can have bad calculation initially -> all entries becomes bad (needs more calibration)
     - It is possible to do handshake several times initially to calculate most accurate latecy
     - With this approach the arudino device should be "calibarted" periodically

Choice 2 is chosen - because even though it can provide many bad results, it can be fixed by excessive and periodically calibration (In Choice 1 you have no control)

**Comment by Spiderixius** [comment]
Completed see commit https://github.com/SuneJepsen/iotproject-arduino/commit/a36aa1a5e9ba0ea7be793e7af9b3e5ed0748f6d5 and https://github.com/SuneJepsen/iotproject-arduino/commit/b491e4fe1e127ee4c05f201d261c76a5e2fa1dfb
